# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ProvenanceWeek 2020
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Following successful past ProvenanceWeek events, ProvenanceWeek 2020 will again co-locate the IPAW and TaPP workshops as well as several satellite events that focus on novel directions for provenance.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "IITDBGroup/ProvenanceWeek2020"

show_excerpts: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - virtual.md
  - tapp.md
  - ipaw.md
  - provviz.md
  - important_dates.md
  - cfp.md
  - location.md
  - news.html
#  - workshops
#  - registration
#  - schedule.md

virtual_event: "June 22nd 9:00am - 3:30pm (eastern)"
long_dates: "June 2021"
short_dates: "06/22-06/25"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
